-- MySQL Script generated by MySQL Workbench
-- Tue Jan 15 22:58:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ep` DEFAULT CHARACTER SET utf8 ;
USE `ep` ;

-- -----------------------------------------------------
-- Table `ep`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`sub_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`sub_categories` (
  `sub_category_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`sub_category_id`),
  INDEX `fk_sub_category_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_sub_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `ep`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`subdivisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`subdivisions` (
  `subdivision_id` INT NOT NULL AUTO_INCREMENT,
  `api_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`subdivision_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `subdivision_id` INT NOT NULL,
  `api_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `fk_departments_subdivisions1_idx` (`subdivision_id` ASC),
  CONSTRAINT `fk_departments_subdivisions1`
    FOREIGN KEY (`subdivision_id`)
    REFERENCES `ep`.`subdivisions` (`subdivision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`education_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`education_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'created',
  `year` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_education_plans_departments1_idx` (`department_id` ASC),
  INDEX `fk_education_plans_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_education_plans_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ep`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_plans_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ep`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`education_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`education_items` (
  `education_item_id` INT NOT NULL AUTO_INCREMENT,
  `sub_category_id` INT NOT NULL,
  `education_plans_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `credits` INT(11) NOT NULL,
  `lectures` INT(11) NULL DEFAULT 0,
  `practice` INT(11) NULL DEFAULT 0,
  `laboratories` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`education_item_id`),
  INDEX `fk_education_items_sub_categories1_idx` (`sub_category_id` ASC),
  INDEX `fk_education_items_education_plans1_idx` (`education_plans_id` ASC),
  INDEX `fk_education_items_subjects1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_education_items_sub_categories1`
    FOREIGN KEY (`sub_category_id`)
    REFERENCES `ep`.`sub_categories` (`sub_category_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_items_education_plans1`
    FOREIGN KEY (`education_plans_id`)
    REFERENCES `ep`.`education_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_education_items_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `ep`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`audit` (
  `audit_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `operation_type` VARCHAR(100) NOT NULL,
  `data` TEXT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`audit_id`),
  INDEX `fk_audit_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_audit_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ep`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`distribution_of_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`distribution_of_hours` (
  `distribution_of_hours_id` INT NOT NULL AUTO_INCREMENT,
  `education_item_id` INT NOT NULL,
  `module_number` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`distribution_of_hours_id`),
  INDEX `fk_distribution_of_hours_education_items2_idx` (`education_item_id` ASC),
  UNIQUE INDEX `field_uniquire` (`module_number` ASC, `education_item_id` ASC),
  CONSTRAINT `fk_distribution_of_hours_education_items2`
    FOREIGN KEY (`education_item_id`)
    REFERENCES `ep`.`education_items` (`education_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`distribution_of_controls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`distribution_of_controls` (
  `distribution_of_controls_id` INT NOT NULL AUTO_INCREMENT,
  `education_item_id` INT NOT NULL,
  `exams` VARCHAR(50) NULL,
  `credit` VARCHAR(50) NULL,
  `individual_tasks` VARCHAR(50) NULL,
  PRIMARY KEY (`distribution_of_controls_id`),
  INDEX `fk_distribution_of_controls_education_items1_idx` (`education_item_id` ASC),
  CONSTRAINT `fk_distribution_of_controls_education_items1`
    FOREIGN KEY (`education_item_id`)
    REFERENCES `ep`.`education_items` (`education_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ep`.`distribution_of_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ep`.`distribution_of_hours` (
  `distribution_of_hours_id` INT NOT NULL AUTO_INCREMENT,
  `education_item_id` INT NOT NULL,
  `module_number` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`distribution_of_hours_id`),
  INDEX `fk_distribution_of_hours_education_items2_idx` (`education_item_id` ASC),
  UNIQUE INDEX `field_uniquire` (`module_number` ASC, `education_item_id` ASC),
  CONSTRAINT `fk_distribution_of_hours_education_items2`
    FOREIGN KEY (`education_item_id`)
    REFERENCES `ep`.`education_items` (`education_item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
